[package]
name = "desc-tool"
version = "0.5.0"
authors = ["swjtusw <swjtusw@126.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust desc-tool package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-base={path="../../component/cyfs-base"}
cyfs-core={path="../../component/cyfs-core"}
async-std = {version = "1.11", features = ["unstable", "attributes"]}
serde_json = "1.0"
clap = "2.34.0"
hex = "0.4"
log = "0.4"
simple_logger = "2.1"
chrono = "0.4"
