[package]
name = "file-manager"
version = "0.5.0"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust file-manager package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
tide = "0.16"
async-std = {version="1.11", features = ["unstable", "attributes"]}
cyfs-base = {path = "../../component/cyfs-base"}
cyfs-util = {path="../../component/cyfs-util"}
rusqlite = { version = "0.27.0", features = ["bundled", "blob"] }
log = "0.4"
cyfs-debug = { path = "../../component/cyfs-debug" }
