[package]
name = "bdt-tool"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust bdt-tool package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-util = { path = '../../component/cyfs-util', version = '0.6' }
cyfs-stack-loader = { path = "../../component/cyfs-stack-loader" }
cyfs-lib = { path = "../../component/cyfs-lib" }
cyfs-noc = { path = "../../component/cyfs-noc" }
cyfs-stack = { path = "../../component/cyfs-stack" }
cyfs-meta-lib = { path = "../../component/cyfs-meta-lib" }
cyfs-base-meta = { path = "../../component/cyfs-base-meta" }
async-std = { version = "1.11", features = ["unstable", "attributes"] }
clap = "2.34.0"
log = "0.4"
md5 = "0.7.0"
rand = "0.7"