[package]
name = "bdt-debuger"
version = "0.5.0"
authors = ["swjtusw <swjtusw@126.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust bdt-debuger package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
async-std = { version = "1.11", features = ["unstable", "attributes"] }
clap = "2.34.0"
log = "0.4"
