[package]
name = "zone-simulator"
version = "0.5.0"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust zone-simulator package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-core = { path = "../../component/cyfs-core" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-stack-loader = { path = "../../component/cyfs-stack-loader", features = [
    "mongo",
    "sqlite",
], default-features = false }
cyfs-lib = { path = "../../component/cyfs-lib" }
cyfs-cip = { path = "../../component/cyfs-cip" }
hex = "0.4"
log = "0.4"
async-std = { version = "1.11", features = ["unstable", "attributes"] }
bip39 = { version = "1.0", features = ["rand", "std"] }
futures = "0.3"
async-trait = "0.1.53"
once_cell = "1.12"
lazy_static = "1.4"
clap = "2.34.0"
