[package]
name = "zone-stack"
version = "0.5.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust zone-stack package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-core = { path = "../../component/cyfs-core" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-stack-loader = { path = "../../component/cyfs-stack-loader", features = [
    "mongo",
    "sqlite",
], default-features = false }
cyfs-lib = { path = "../../component/cyfs-lib" }
cyfs-cip = { path = "../../component/cyfs-cip" }
hex = "0.4"
log = "0.4"
async-std = { version = "1.11", features = ["unstable", "attributes"] }
bip39 = { version = "1.0", default-features = false }
futures = "0.3"
async-trait = "0.1.53"
zone-simulator = { path = "../../tools/zone-simulator" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
clap = "2.34.0"
