[package]
name = "meta-stat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-base= {path="../../component/cyfs-base"}
async-std = { version = "1.11", features = ["attributes"] }
async-trait = "0.1.53"
sqlx = { version = "0.6", features = [ "runtime-async-std-rustls", "sqlite", "macros" ] }
log = "0.4"
simple_logger = "3.0"
clap = "2.34.0"
once_cell = "1.12"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
surf = { version = '2.3.2', default-features = false, features = ['h1-client-rustls'] }
comfy-table = "6.1.2"
toml = "0.5"
plotters = "0.3.3"
lettre = "0.9"
lettre_email = "0.9"
mime = "0.3.13"
chrono = "0.4"
timer = "0.2"
rand = '0.7'