[package]
name = "dsg-miner"
version = "0.5.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust dsg-miner package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dsg_miner"
path = "./src/lib.rs"

[dependencies]
log = "0.4.16"
async-std = { version = "1.8", features = ["std"] }
futures = { version = "0.3", features = ["default"] }
async-trait = "0.1.53"
cyfs-debug = { path = "../../../component/cyfs-debug" }
cyfs-base = { path = "../../../component/cyfs-base" }
cyfs-core = { path = "../../../component/cyfs-core" }
cyfs-bdt = { path = "../../../component/cyfs-bdt" }
cyfs-util = { path = "../../../component/cyfs-util" }
cyfs-lib = { path = "../../../component/cyfs-lib" }
dsg-client = { path = "../client" }
