[package]
name = "cyfs-runtime"
version = "0.5.0"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust cyfs-runtime package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["sqlite"], default-features = false }
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-lib = { path = "../../component/cyfs-lib" }
cyfs-stack-loader = { path = "../../component/cyfs-stack-loader", features = [
    "sqlite",
], default-features = false }
ood-control = { path = "../../service/ood-control" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
async-std = { version = "1.11", features = ["attributes"] }
async-trait = "0.1.53"
futures = "0.3"
async-h1 = "2.3.3"
clap = "2.34.0"
url = "2.2"
bytes = "1.1"
dirs = "4.0"
tide = "0.16"
http-types = "2.12"
mime-sniffer = "0.1.2"
toml = "0.5"
once_cell = "1.12"
rand = "0.7"
formdata = "0.13"
hyper = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"
android_logger = "0.11"

[lib]
name = "cyfsruntime"
crate-type = ["cdylib"]
